### ISSUE TITLE
Unexpected colors in DimPlot from 11-1-Atlas_FindMarkers notebook

### ISSUE THREAD

**Issue by voichek** [Hsu-Che-Wei/COPILOT#7]
Dear Che-Wei,

First of all, thank you for your comprehensive and easy-to-follow guide. I am new to this type of analysis and have run into an issue while trying to reproduce the first two graphs from the "Cell type specific markers in WT Arabidopsis roots" section of your manual.

For some reason I get the coloring wrong in the graph (attached). Can you direct me to how to modify it?
[root_cell_first_analysis.html.zip](https://github.com/Hsu-Che-Wei/COPILOT/files/11591924/root_cell_first_analysis.html.zip)

Best,
Yoav

**Comment by Hsu-Che-Wei** [comment]
Hi Yoav,

The annotation of the atlas has been updated according to our recently published paper: 
https://www.science.org/doi/10.1126/science.adf4721

The celltype.anno by default now contains sub-celltype. Therefore, the xylem and phloem are split into metaxylem, protoxylem, protophloem, companion cells and metaphloem. 

I believe that the metadata of the Seurat object also contains labels with the suffix ".crude". This is the version without sub-celltype, and is the one that should be used in the notebook.  

Best,
Che-Wei

**Comment by voichek** [comment]
Dear Che-Wei,

Thanks for the quick reply! I was just worried that there was some glitch in the database file.

Best,
Yoav
